inherit_from: .rubocop_todo.yml


AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

BlockLength:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ArrayCoercion:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
  - 'app/controllers/users/confirmations_controller.rb'
  - 'app/controllers/users/omniauth_callbacks_controller.rb'
  - 'app/controllers/users/passwords_controller.rb'
  - 'app/controllers/users/registrations_controller.rb'
  - 'app/controllers/users/sessions_controller.rb'
  - 'app/controllers/users/unlocks_controller.rb'

Metrics/AbcSize:
  Exclude: 
    - 'app/controllers/comments_controller.rb'
    - 'app/models/user.rb'
    
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'config/initializers/devise.rb'
    - 'app/models/user.rb'