version: '3'
services:
  db:
    image: postgres
    env_file: 
      - ./.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: .
    environment:
      SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/further_efforts
    ports:
      - "3000:3000"
    depends_on:
      - db