default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  username: root
  password: password
  host: db

development:
  <<: *default
  database: further_efforts_development

test:
  <<: *default
  database: further_efforts_test

production:
  <<: *default
  adaptrer: mysql2
  encoding: utf8
  pool: 5